### PR TITLE
[WIP] Async ondemand: the "lazy" approach

### PR DESCRIPTION
**Pull request by yohanboniface**
- remove all the ondemand parameters logic
- add an "lazy" parameter to the route decorator
- add a "headers" hooks, ran before the request is consumed
- add a per-view hooks mecanism

## TODO

- [x] unittest the pause/resume reading workflow
- [ ] decide the route parameter name (`lazy` atm)
- [ ] decide if we use the same decorator for the view specific hook, and decide the naming (`listen` atm)
- [ ] decide the async response streaming workflow
- [ ] decide about python3.5 support

### CODE REVIEW

**Comment by yohanboniface** [comment]
python3.5 is failing because we use [AsyncGenerator](https://docs.python.org/3.7/library/collections.abc.html#collections.abc.AsyncGenerator), should we remove 3.5 support if we go this way?

**Comment by trollfot** [comment]
> python3.5 is failing because we use [AsyncGenerator](https://docs.python.org/3.7/library/collections.abc.html#collections.abc.AsyncGenerator), should we remove 3.5 support if we go this way?

As a policy, supporting the last 2 major versions only is not shabby.

**Comment by davidbgk** [comment]
> should we remove 3.5 support if we go this way?

I have no strong opinion about that.

**Comment by yohanboniface** [comment]
Another Queue pattern, but slower as it is:

```diff
diff --git a/roll/http.py b/roll/http.py
index 0e305a3..e158cf8 100644
--- a/roll/http.py
+++ b/roll/http.py
@@ -208,7 +208,7 @@ class HTTPProtocol(asyncio.Protocol):
                 self.response.body = error.message
             else:
                 self.response.status = HTTPStatus.BAD_REQUEST
-                self.response.body = b'Unparsable request'
+                self.response.body = f'Unparsable request: {error.__context__}'
             self.task = self.app.loop.create_task(self.write())
 
     async def upgraded(self):
@@ -229,7 +229,7 @@ class HTTPProtocol(asyncio.Protocol):
 
     def on_body(self, data: bytes):
         # Save the first chunk.
-        self.request.queue.put(data)
+        self.request.stream.chunks.put_nowait(data)
         # And let the user decide if we should continue reading or not.
         self.pause_reading()
 
@@ -246,7 +246,7 @@ class HTTPProtocol(asyncio.Protocol):
         self.response = self.app.Response(self.app, self)
 
     def on_message_complete(self):
-        self.request.queue.end()
+        self.request.stream.chunks.put_nowait(None)
 
     def on_headers_complete(self):
         if self.parser.should_upgrade():
diff --git a/roll/io.py b/roll/io.py
index 640dac3..97c8389 100644
--- a/roll/io.py
+++ b/roll/io.py
@@ -1,5 +1,5 @@
-from asyncio import Event
-from queue import deque
+from asyncio import Queue, Future
+# from concurrent.futures import Future
 from http import HTTPStatus
 from urllib.parse import parse_qs
 
@@ -17,46 +17,37 @@ except ImportError:
     from json.decoder import JSONDecodeError
 
 
-class StreamQueue:
+class Stream(Future):
 
     def __init__(self):
-        self.items = deque()
-        self.event = Event()
-        self.waiting = False
-        self.dirty = False
-        self.finished = False
+        super().__init__()
+        self.chunks = Queue()
+
+    def empty(self):
+        return self.chunks.empty()
 
     async def get(self):
-        try:
-            return self.items.popleft()
-        except IndexError:
-            if self.finished is True:
-                return b''
+        if not self.done():
+            chunk = await self.chunks.get()
+            self.chunks.task_done()
+            return chunk
+        raise RuntimeError('Body has been exhausted.')
+
+    async def put(self, value):
+        if not self.done():
+            return await self.chunks.put(value)
+        raise RuntimeError('Body was terminated.')
+
+    async def __aiter__(self):
+        while not self.done():
+            chunk = await self.chunks.get()
+            self.chunks.task_done()
+            if chunk is None:
+                self.set_result(True)
+            elif isinstance(chunk, Exception):
+                self.set_exception(chunk)
             else:
-                self.event.clear()
-                self.waiting = True
-                await self.event.wait()
-                self.event.clear()
-                self.waiting = False
-                return self.items.popleft()
-
-    def put(self, item):
-        self.dirty = True
-        self.items.append(item)
-        if self.waiting is True:
-            self.event.set()
-
-    def clear(self):
-        if self.dirty:
-            self.items.clear()
-            self.event.clear()
-            self.dirty = False
-        self.finished = False
-
-    def end(self):
-        if self.waiting:
-            self.put(None)
-        self.finished = True
+                yield chunk
 
 
 class Request(dict):
@@ -67,13 +58,13 @@ class Request(dict):
     __slots__ = (
         'app', 'url', 'path', 'query_string', '_query', '_body',
         'method', '_chunk', 'headers', 'route', '_cookies', '_form', '_files',
-        'upgrade', 'protocol', '_json', 'queue'
+        'upgrade', 'protocol', '_json', 'stream'
     )
 
     def __init__(self, app, protocol):
         self.app = app
         self.protocol = protocol
-        self.queue = StreamQueue()
+        self.stream = Stream()
         self.headers = {}
         self._body = None
         self._chunk = b''
@@ -165,21 +156,16 @@ class Request(dict):
         self._body = data
 
     async def read(self):
-        if not self._body:
+        if self._body is None:
             self._body = b''
             async for chunk in self:
                 self._body += chunk
         return self._body
 
     async def __aiter__(self):
-        # TODO raise if already consumed?
-        while True:
-            self.protocol.resume_reading()
-            data = await self.queue.get()
-            if not data:
-                break
-            self.protocol.pause_reading()
-            yield data
+        self.protocol.resume_reading()
+        async for chunk in self.stream:
+            yield chunk
 
 
 class Response:
```

**Comment by yohanboniface** [comment]
@trollfot I had a test at integrating the branch async_request_body, but tests are failing.

I made some fixes, but there is still work needed and I'm moving offline. I wonder if we don't have a race condition, because we rely on `self.complete` to decide if data needs to be returned, while is always set at `on_message_complete`, but stream can be consumed afterward. I may be missing something.

Here the last diff:

```diff
diff --git a/roll/http.py b/roll/http.py
index 0e305a3..0e8e9f9 100644
--- a/roll/http.py
+++ b/roll/http.py
@@ -208,7 +208,7 @@ class HTTPProtocol(asyncio.Protocol):
                 self.response.body = error.message
             else:
                 self.response.status = HTTPStatus.BAD_REQUEST
-                self.response.body = b'Unparsable request'
+                self.response.body = f'Unparsable request: {error.__context__}'
             self.task = self.app.loop.create_task(self.write())
 
     async def upgraded(self):
@@ -228,10 +228,7 @@ class HTTPProtocol(asyncio.Protocol):
         self.request.headers[name.decode().upper()] = value.decode()
 
     def on_body(self, data: bytes):
-        # Save the first chunk.
-        self.request.queue.put(data)
-        # And let the user decide if we should continue reading or not.
-        self.pause_reading()
+        self.request.stream.put(data)
 
     def on_url(self, url: bytes):
         self.request.method = self.parser.get_method().decode().upper()
@@ -246,7 +243,7 @@ class HTTPProtocol(asyncio.Protocol):
         self.response = self.app.Response(self.app, self)
 
     def on_message_complete(self):
-        self.request.queue.end()
+        self.request.stream.complete.set()
 
     def on_headers_complete(self):
         if self.parser.should_upgrade():
diff --git a/roll/io.py b/roll/io.py
index 640dac3..29cfdfc 100644
--- a/roll/io.py
+++ b/roll/io.py
@@ -1,3 +1,4 @@
+import asyncio
 from asyncio import Event
 from queue import deque
 from http import HTTPStatus
@@ -17,46 +18,38 @@ except ImportError:
     from json.decoder import JSONDecodeError
 
 
-class StreamQueue:
+class Stream(deque):
 
-    def __init__(self):
-        self.items = deque()
-        self.event = Event()
-        self.waiting = False
-        self.dirty = False
-        self.finished = False
+    def __init__(self, protocol):
+        super().__init__()
+        self.protocol = protocol
+        self.complete = Event()
+        self.unread = Event()
+
+    @property
+    def completed(self):
+        return self.complete.is_set()
+
+    def put(self, data: bytes):
+        self.append(data)
+        self.unread.set()
+        self.protocol.pause_reading()
 
     async def get(self):
-        try:
-            return self.items.popleft()
-        except IndexError:
-            if self.finished is True:
-                return b''
-            else:
-                self.event.clear()
-                self.waiting = True
-                await self.event.wait()
-                self.event.clear()
-                self.waiting = False
-                return self.items.popleft()
-
-    def put(self, item):
-        self.dirty = True
-        self.items.append(item)
-        if self.waiting is True:
-            self.event.set()
-
-    def clear(self):
-        if self.dirty:
-            self.items.clear()
-            self.event.clear()
-            self.dirty = False
-        self.finished = False
-
-    def end(self):
-        if self.waiting:
-            self.put(None)
-        self.finished = True
+        await asyncio.wait((self.unread.wait(), self.complete.wait()))
+        if self.completed:
+            return None
+        chunk = self.popleft()
+        self.unread.clear()
+        self.protocol.resume_reading()
+        return chunk
+
+    async def __aiter__(self):
+        while True:
+            chunk = await self.get()
+            if chunk is None:
+                break
+            yield chunk
 
 
 class Request(dict):
@@ -67,16 +60,15 @@ class Request(dict):
     __slots__ = (
         'app', 'url', 'path', 'query_string', '_query', '_body',
         'method', '_chunk', 'headers', 'route', '_cookies', '_form', '_files',
-        'upgrade', 'protocol', '_json', 'queue'
+        'upgrade', 'protocol', '_json', 'stream'
     )
 
     def __init__(self, app, protocol):
         self.app = app
         self.protocol = protocol
-        self.queue = StreamQueue()
+        self.stream = Stream(protocol)
         self.headers = {}
         self._body = None
-        self._chunk = b''
         self.method = None
         self.upgrade = None
         self._cookies = None
@@ -166,20 +158,13 @@ class Request(dict):
 
     async def read(self):
         if not self._body:
-            self._body = b''
-            async for chunk in self:
-                self._body += chunk
+            await self.stream.complete.wait()
+            self._body = b''.join(self.stream)
         return self._body
 
     async def __aiter__(self):
-        # TODO raise if already consumed?
-        while True:
-            self.protocol.resume_reading()
-            data = await self.queue.get()
-            if not data:
-                break
-            self.protocol.pause_reading()
-            yield data
+        async for chunk in self.stream:
+            yield chunk
 
 
 class Response:
diff --git a/tests/test_request.py b/tests/test_request.py
index 94314ff..32243a8 100644
--- a/tests/test_request.py
+++ b/tests/test_request.py
@@ -586,7 +586,7 @@ async def test_can_consume_lazy_request_iterating(client, app):
     @app.route('/test', methods=['POST'], lazy=True)
     async def post(req, resp):
         async for chunk in req:
-            resp.body = chunk
+            resp.body += chunk
 
     resp = await client.post('/test', data='blah'*1000)
     assert resp.status == HTTPStatus.OK
```

**Comment by davidbgk** [comment]
> decide about python3.5 support

One year later, I think we can drop the support for 3.5

> decide the route parameter name (`lazy` atm)

Maybe `deferred` or `postponed` would be more explicit.

**Comment by davidbgk** [comment]
> decide if we use the same decorator for the view specific hook, and decide the naming (`listen` atm)

Is there another usage besides parsing headers before reading the body? If no, maybe an explicit name about headers?

**Comment by yohanboniface** [comment]
Partly merged with #89. #227 will add the `headers` event. No call for a per-view hook mechanism for now.

**Pull request closed without merging**
