### PR TITLE
Functional websockets

### PR DESCRIPTION
**Pull request by trollfot**
Using WSProtocol as the main protocol doesn't alter the performances. I benchmarked with Roll and WSRoll and the results are identical.

There is a folder with a ready-to-use example "ws_examples". It contains a websocket.html and the code for a very basic chat.

One of the test is passing but should be modified once we figure out what to do with a misbehaving ws handler.

### CODE REVIEW

**Comment by yohanboniface** [comment]
Thanks @trollfot!
We've made a first review of your work, sounds good, congrats :)
This first review had the specific goal of understanding what is the impact on Roll core, whether this ends as a plugin or not. We have no conclusion yet. ;)
Basically, the `if websocket` here and there seems to show that the Roll structure needs to evolve to make the branching standard/websocket more natural.
May it be by moving a bit of business from Protocol to Response so we can have a Websocket class that would step in, while keeping Roll and Protocol unaware? That needs more investigation.
Also in the case we finally arbitrate for a plugin, one option to use a bit more Roll internals could be to add a `route` hook, that would prevent the need for a `WSRoll` class with a custom `route` method (in this topic, you could use the `on_error` hook for the `print_exc`).
Anyway, that was just a first feedback, we need a bit more time to rethink Roll to welcome websockets ;)

Stay tuned! :)

**Comment by trollfot** [comment]
Maybe I could give it a shot ? I thought a bit about it and maybe we could introduce something that glues the Protocol and the Request/Response together, allowing for more pluggability without being too generic as over-thought pluggability is very often a long term disaster :)

**Comment by yohanboniface** [comment]
> Maybe I could give it a shot ?

Sure! Please do not refrain if you want to :)

> I thought a bit about it and maybe we could introduce something that glues the Protocol and the Request/Response together, allowing for more pluggability without being too generic

That's the exact opposite of what I had in mind, and thus I like this option :p
Just keep in mind that going that road may be long and full of (peaceful but obstinate but peaceful) discussions ;)

> over-thought pluggability is very often a long term disaster :)

Yeah, that's a subtle line.

**Comment by trollfot** [comment]
In-depth discussion about such decisions is important. I'll propose and you can decide if it's worth a consideration or not.

**Comment by yohanboniface** [comment]
Closing in favor of #50

**Pull request closed without merging**
